# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rake db:seed (or created alongside the db with db:setup).
#
# Examples:
#
#   cities = City.create([{ name: 'Chicago' }, { name: 'Copenhagen' }])
#   Mayor.create(name: 'Emanuel', city: cities.first)

Post.create(name: "veetine", team_elo: 1800, team_name: 'blah')
Post.create(name: "shaosters", team_elo: 1800, team_name: 'blah')
Post.create(name: "Minday Nam", team_elo: 1800, team_name: 'blah')
Post.create(name: "Sycho Squid", team_elo: 1800, team_name: 'blah')
Post.create(name: "BIoodWater", team_elo: 1800, team_name: 'blah')
Post.create(name: "AriesLL", team_elo: 1800, team_name: 'blah')
Post.create(name: "L0cust", team_elo: 1800, team_name: 'blah')
Post.create(name: "Quantic Hai", team_elo: 1800, team_name: 'blah')


# Post.create(name: "Onionbagel", team_elo: 1800, team_name: "blah")
# Post.create(name: "Cris", team_elo: 1800, team_name: "blah")
# Post.create(name: "JRTSeven", team_elo: 1800, team_name: "blah")
# Post.create(name: "Dyrus", team_elo: 1800, team_name: "blah")
# Post.create(name: "Sorbooze", team_elo: 1800, team_name: "blah")
# Post.create(name: "DeeZy", team_elo: 1800, team_name: "blah")
# Post.create(name: "Valkrin", team_elo: 1800, team_name: "blah")
# Post.create(name: "Hashinshin", team_elo: 1800, team_name: "blah")
# Post.create(name: "Raffito", team_elo: 1800, team_name: "blah")
# Post.create(name: "ozadin", team_elo: 1800, team_name: "blah")
# Post.create(name: "aL Spellsy", team_elo: 1800, team_name: "blah")
# Post.create(name: "L0CUST", team_elo: 1800, team_name: "blah")
# Post.create(name: "Nickwu", team_elo: 1800, team_name: "blah")
# Post.create(name: "Monsoonz", team_elo: 1800, team_name: "blah")
# Post.create(name: "WildTurtle", team_elo: 1800, team_name: "blah")
# Post.create(name: "jungie", team_elo: 1800, team_name: "blah")
# Post.create(name: "Rainbrain", team_elo: 1800, team_name: "blah")
# Post.create(name: "scarratine", team_elo: 1800, team_name: "blah")
# Post.create(name: "GadGeta", team_elo: 1800, team_name: "blah")
# Post.create(name: "chaseonfireeeee", team_elo: 1800, team_name: "blah")
# Post.create(name: "CLG Wickd", team_elo: 1800, team_name: "blah")
# Post.create(name: "Diamond", team_elo: 1800, team_name: "blah")
# Post.create(name: "sharks", team_elo: 1800, team_name: "blah")
# Post.create(name: "Genre", team_elo: 1800, team_name: "blah")
# Post.create(name: "DudeImAzn", team_elo: 1800, team_name: "blah")
# Post.create(name: "scarratine", team_elo: 1800, team_name: "blah")
# Post.create(name: "Jintae", team_elo: 1800, team_name: "blah")
# Post.create(name: "Suzashi", team_elo: 1800, team_name: "blah")
# Post.create(name: "GagA1", team_elo: 1800, team_name: "blah")
# Post.create(name: "Neverlike", team_elo: 1800, team_name: "blah")
# Post.create(name: "Ki11Face", team_elo: 1800, team_name: "blah")
# Post.create(name: "loveryloverin", team_elo: 1800, team_name: "blah")
# Post.create(name: "eFIVE", team_elo: 1800, team_name: "blah")
# Post.create(name: "Defuse23", team_elo: 1800, team_name: "blah")
# Post.create(name: "Easy", team_elo: 1800, team_name: "blah")
# Post.create(name: "toshibu", team_elo: 1800, team_name: "blah")
# Post.create(name: "Newbert", team_elo: 1800, team_name: "blah")
# Post.create(name: "Chief Minky", team_elo: 1800, team_name: "blah")
# Post.create(name: "Quikz", team_elo: 1800, team_name: "blah")
# Post.create(name: "Feithers", team_elo: 1800, team_name: "blah")
# Post.create(name: "Neurocraft", team_elo: 1800, team_name: "blah")
# Post.create(name: "Zeforus", team_elo: 1800, team_name: "blah")
# Post.create(name: "Nerek", team_elo: 1800, team_name: "blah")
# Post.create(name: "Rhux", team_elo: 1800, team_name: "blah")
# Post.create(name: "Tanochimpos", team_elo: 1800, team_name: "blah")
# Post.create(name: "Okuser", team_elo: 1800, team_name: "blah")
# Post.create(name: "Izaiah", team_elo: 1800, team_name: "blah")
# Post.create(name: "DarkTerrorZ", team_elo: 1800, team_name: "blah")
# Post.create(name: "RevengeBlade", team_elo: 1800, team_name: "blah")
# Post.create(name: "JRTSeven", team_elo: 1800, team_name: "blah")
# Post.create(name: "PaprikaCC", team_elo: 1800, team_name: "blah")
# Post.create(name: "DynamicFall", team_elo: 1800, team_name: "blah")
# Post.create(name: "Astronaut", team_elo: 1800, team_name: "blah")
# Post.create(name: "dx30", team_elo: 1800, team_name: "blah")
# Post.create(name: "ChickenWalker", team_elo: 1800, team_name: "blah")
# Post.create(name: "Normalize", team_elo: 1800, team_name: "blah")
# Post.create(name: "Next", team_elo: 1800, team_name: "blah")
# Post.create(name: "isotope", team_elo: 1800, team_name: "blah")
# Post.create(name: "Crimelord", team_elo: 1800, team_name: "blah")
# Post.create(name: "TummyTuck", team_elo: 1800, team_name: "blah")
# Post.create(name: "Mirabis", team_elo: 1800, team_name: "blah")
# Post.create(name: "Gummyrat", team_elo: 1800, team_name: "blah")
# Post.create(name: "Dphat", team_elo: 1800, team_name: "blah")
# Post.create(name: "Nikantor", team_elo: 1800, team_name: "blah")
# Post.create(name: "Riosilve", team_elo: 1800, team_name: "blah")
# Post.create(name: "Dexirian", team_elo: 1800, team_name: "blah")
# Post.create(name: "redCoupa", team_elo: 1800, team_name: "blah")
# Post.create(name: "PawnGypsy", team_elo: 1800, team_name: "blah")
# Post.create(name: "Thth", team_elo: 1800, team_name: "blah")
# Post.create(name: "AtIanta", team_elo: 1800, team_name: "blah")
# Post.create(name: "GeekGoneMAD", team_elo: 1800, team_name: "blah")
# Post.create(name: "Dungastu", team_elo: 1800, team_name: "blah")
# Post.create(name: "Synyard", team_elo: 1800, team_name: "blah")
# Post.create(name: "CarterV15", team_elo: 1800, team_name: "blah")
# Post.create(name: "LuckyWarrior", team_elo: 1800, team_name: "blah")
# Post.create(name: "Styx", team_elo: 1800, team_name: "blah")
# Post.create(name: "AWildMiMo", team_elo: 1800, team_name: "blah")
# Post.create(name: "Dis", team_elo: 1800, team_name: "blah")
# Post.create(name: "Yiruru", team_elo: 1800, team_name: "blah")
# Post.create(name: "huebear", team_elo: 1800, team_name: "blah")
# Post.create(name: "Ishu55", team_elo: 1800, team_name: "blah")
# Post.create(name: "AbstractCool", team_elo: 1800, team_name: "blah")
# Post.create(name: "Lipsticks", team_elo: 1800, team_name: "blah")
# Post.create(name: "Sheol", team_elo: 1800, team_name: "blah")
# Post.create(name: "Iucent", team_elo: 1800, team_name: "blah")
# Post.create(name: "UhKill", team_elo: 1800, team_name: "blah")
# Post.create(name: "Sodapizop", team_elo: 1800, team_name: "blah")
# Post.create(name: "brom9663", team_elo: 1800, team_name: "blah")
# Post.create(name: "Guibo", team_elo: 1800, team_name: "blah")
# Post.create(name: "SlothFetish", team_elo: 1800, team_name: "blah")
# Post.create(name: "TonyWin", team_elo: 1800, team_name: "blah")
# Post.create(name: "hustling", team_elo: 1800, team_name: "blah")
# Post.create(name: "SoKorean", team_elo: 1800, team_name: "blah")
# Post.create(name: "silphire", team_elo: 1800, team_name: "blah")
# Post.create(name: "ExecutionerKen", team_elo: 1800, team_name: "blah")
# Post.create(name: "Blagon", team_elo: 1800, team_name: "blah")
# Post.create(name: "Graymanse", team_elo: 1800, team_name: "blah")
# Post.create(name: "EstebanMegaK", team_elo: 1800, team_name: "blah")
# Post.create(name: "Honu", team_elo: 1800, team_name: "blah")
# Post.create(name: "Csiril", team_elo: 1800, team_name: "blah")
# Post.create(name: "sL Sainta Claws", team_elo: 1800, team_name: "blah")
# Post.create(name: "Hoodstomp", team_elo: 1800, team_name: "blah")
# Post.create(name: "Nxzl IA T AI", team_elo: 1800, team_name: "blah")
# Post.create(name: "hafu", team_elo: 1800, team_name: "blah")
# Post.create(name: "DragonBleu", team_elo: 1800, team_name: "blah")
# Post.create(name: "marann", team_elo: 1800, team_name: "blah")
# Post.create(name: "teraares", team_elo: 1800, team_name: "blah")
# Post.create(name: "FallenBandit", team_elo: 1800, team_name: "blah")
# Post.create(name: "MarineRevenge", team_elo: 1800, team_name: "blah")
# Post.create(name: "RODRIGO160", team_elo: 1800, team_name: "blah")
# Post.create(name: "COS MIA", team_elo: 1800, team_name: "blah")

